additionalArguments:
  - "--entrypoints.web.address=:80"
  - "--entrypoints.websecure.address=:443"
  - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
  - "--certificatesresolvers.letsencrypt.acme.email=sten.heimbrodt@hotmail.de"
  - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"

persistence:
  enabled: true
  name: traefik-acme
  accessMode: ReadWriteOnce
  size: 1Gi
  path: /data

ports:
  web:
    expose:
      default: true
    port: 80
    protocol: TCP

  websecure:
    expose:
      default: true
    port: 443
    protocol: TCP