apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgres-db
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      nodePort: 30432